/*
 * generated by Xtext
 */
package UseCaseDSL;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UseCaseUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return UseCaseDSL.ui.internal.UseCaseActivator.getInstance().getInjector("UseCaseDSL.UseCase");
	}
	
}
