<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmn2" nsURI="platform:/plugin/bpmn2/model/Bpmn2.ecore" nsPrefix="bpmn2">
  <eClassifiers xsi:type="ecore:EClass" name="BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1" iD="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" abstract="true" eSuperTypes="//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowNode" abstract="true" eSuperTypes="//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//SequenceFlow" eOpposite="//SequenceFlow/sourceRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//SequenceFlow" eOpposite="//SequenceFlow/targetRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRef" lowerBound="1" eType="//FlowNode" eOpposite="//FlowNode/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRef" lowerBound="1" eType="//FlowNode" eOpposite="//FlowNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionExpression" upperBound="-1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="//FlowNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallableElement" eSuperTypes="//RootElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatchEvent" abstract="true" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Definitions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootElements" upperBound="-1" eType="//RootElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNamespace" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1" eType="//Definitions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="//ThrowEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventBasedGateway" eSuperTypes="//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveGateway" eSuperTypes="//Gateway">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="//SequenceFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="//BaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElementsContainer" abstract="true" eSuperTypes="//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="laneSets" upperBound="-1" eType="//LaneSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowElements" upperBound="-1" eType="//FlowElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalExpression" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" abstract="true" eSuperTypes="//FlowNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gatewayDirection" ordered="false" lowerBound="1" eType="//GatewayDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GatewayDirection">
    <eLiterals name="Converging" value="1" literal="Converging"/>
    <eLiterals name="Diverging" value="2" literal="Diverging"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateCatchEvent" eSuperTypes="//CatchEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateThrowEvent" eSuperTypes="//ThrowEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lane">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowNodeRefs" upperBound="-1" eType="//FlowNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1" iD="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LaneSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lanes" upperBound="-1" eType="//Lane" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1" iD="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManualTask" eSuperTypes="//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelGateway" eSuperTypes="//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="//CallableElement //FlowElementsContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceTask" eSuperTypes="//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="//CatchEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="//Activity //InteractionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="//FlowNode //InteractionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThrowEvent" abstract="true" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserTask" eSuperTypes="//Task"/>
</ecore:EPackage>
