/*
 * generated by Xtext
 */
package UseCaseDSL.ui.contentassist

import UseCaseDSL.ui.contentassist.AbstractUseCaseProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class UseCaseProposalProvider extends AbstractUseCaseProposalProvider {
}
