/*
* generated by Xtext
*/
package UseCaseDSL;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class UseCaseStandaloneSetup extends UseCaseStandaloneSetupGenerated{

	public static void doSetup() {
		new UseCaseStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

