/*
 * generated by Xtext
 */
package UseCaseDSL.serializer;

import UseCaseDSL.Actor;
import UseCaseDSL.AlternativeFlow;
import UseCaseDSL.AlternativeFlowAlternative;
import UseCaseDSL.BasicFlow;
import UseCaseDSL.Condition;
import UseCaseDSL.ExceptionFlow;
import UseCaseDSL.LocalAlternative;
import UseCaseDSL.NormalStep;
import UseCaseDSL.PackageDeclaration;
import UseCaseDSL.ParallelFlow;
import UseCaseDSL.ParallelStep;
import UseCaseDSL.UCCondition;
import UseCaseDSL.UseCase;
import UseCaseDSL.UseCaseDSLPackage;
import UseCaseDSL.UseCasesModel;
import UseCaseDSL.services.UseCaseGrammarAccess;
import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public abstract class AbstractUseCaseSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private UseCaseGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == UseCaseDSLPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case UseCaseDSLPackage.ACTOR:
				sequence_Actor(context, (Actor) semanticObject); 
				return; 
			case UseCaseDSLPackage.ALTERNATIVE_FLOW:
				sequence_AlternativeFlow(context, (AlternativeFlow) semanticObject); 
				return; 
			case UseCaseDSLPackage.ALTERNATIVE_FLOW_ALTERNATIVE:
				sequence_AlternativeFlowAlternative(context, (AlternativeFlowAlternative) semanticObject); 
				return; 
			case UseCaseDSLPackage.BASIC_FLOW:
				sequence_BasicFlow(context, (BasicFlow) semanticObject); 
				return; 
			case UseCaseDSLPackage.CONDITION:
				sequence_Condition(context, (Condition) semanticObject); 
				return; 
			case UseCaseDSLPackage.EXCEPTION_FLOW:
				sequence_ExceptionFlow(context, (ExceptionFlow) semanticObject); 
				return; 
			case UseCaseDSLPackage.LOCAL_ALTERNATIVE:
				sequence_LocalAlternative(context, (LocalAlternative) semanticObject); 
				return; 
			case UseCaseDSLPackage.NORMAL_STEP:
				sequence_NormalStep(context, (NormalStep) semanticObject); 
				return; 
			case UseCaseDSLPackage.PACKAGE_DECLARATION:
				sequence_PackageDeclaration(context, (PackageDeclaration) semanticObject); 
				return; 
			case UseCaseDSLPackage.PARALLEL_FLOW:
				sequence_ParallelFlow(context, (ParallelFlow) semanticObject); 
				return; 
			case UseCaseDSLPackage.PARALLEL_STEP:
				sequence_ParallelStep(context, (ParallelStep) semanticObject); 
				return; 
			case UseCaseDSLPackage.UC_CONDITION:
				sequence_UCCondition(context, (UCCondition) semanticObject); 
				return; 
			case UseCaseDSLPackage.USE_CASE:
				sequence_UseCase(context, (UseCase) semanticObject); 
				return; 
			case UseCaseDSLPackage.USE_CASES_MODEL:
				sequence_UseCasesModel(context, (UseCasesModel) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (name=ID type=ActorType description=STRING? extends=[Actor|ID]?)
	 */
	protected void sequence_Actor(EObject context, Actor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (condition=STRING ref=[NamedFlow|ID] continuation=[Step|ID]?)
	 */
	protected void sequence_AlternativeFlowAlternative(EObject context, AlternativeFlowAlternative semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID steps+=Step* finalState=UCCondition?)
	 */
	protected void sequence_AlternativeFlow(EObject context, AlternativeFlow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (steps+=Step* finalState=UCCondition?)
	 */
	protected void sequence_BasicFlow(EObject context, BasicFlow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (condition=STRING continuation=[Step|ID]?)
	 */
	protected void sequence_Condition(EObject context, Condition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID condition=STRING steps+=Step* finalState=UCCondition?)
	 */
	protected void sequence_ExceptionFlow(EObject context, ExceptionFlow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (condition=STRING (description=STRING | invokedUseCase=[UseCase|ID]) continuation=[Step|ID]?)
	 */
	protected void sequence_LocalAlternative(EObject context, LocalAlternative semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         label=STRING? 
	 *         type=StepType 
	 *         actor=[Actor|ID] 
	 *         (stepAlternative+=StepAlternative+ | invokedUseCase=[UseCase|ID])? 
	 *         next=[Step|ID]?
	 *     )
	 */
	protected void sequence_NormalStep(EObject context, NormalStep semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=QualifiedName description=STRING? actors+=Actor* useCases+=UseCase*)
	 */
	protected void sequence_PackageDeclaration(EObject context, PackageDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID steps+=Step* finalState=UCCondition?)
	 */
	protected void sequence_ParallelFlow(EObject context, ParallelFlow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID label=STRING? invokedFlows+=[ParallelFlow|ID] invokedFlows+=[ParallelFlow|ID]* next=[Step|ID]?)
	 */
	protected void sequence_ParallelStep(EObject context, ParallelStep semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     name=STRING
	 */
	protected void sequence_UCCondition(EObject context, UCCondition semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, UseCaseDSLPackage.Literals.UC_CONDITION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UseCaseDSLPackage.Literals.UC_CONDITION__NAME));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getUCConditionAccess().getNameSTRINGTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         description=STRING? 
	 *         superCase=[UseCase|ID]? 
	 *         preconditions+=UCCondition* 
	 *         postconditions+=UCCondition* 
	 *         flows+=Flow*
	 *     )
	 */
	protected void sequence_UseCase(EObject context, UseCase semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     packages+=PackageDeclaration*
	 */
	protected void sequence_UseCasesModel(EObject context, UseCasesModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
}
