/*
 * generated by Xtext
 */
package UseCaseDSL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UseCaseUiModule extends UseCaseDSL.ui.AbstractUseCaseUiModule {
	public UseCaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
