/**
 * generated by Xtext
 */
package UseCaseDSL.serializer;

import UseCaseDSL.serializer.AbstractUseCaseSemanticSequencer;

@SuppressWarnings("all")
public class UseCaseSemanticSequencer extends AbstractUseCaseSemanticSequencer {
}
