/**
 * generated by Xtext
 */
package UseCaseDSL.serializer;

import UseCaseDSL.serializer.AbstractUseCaseSyntacticSequencer;

@SuppressWarnings("all")
public class UseCaseSyntacticSequencer extends AbstractUseCaseSyntacticSequencer {
}
